name: Daily Stock Checker

on:
  workflow_dispatch:
  schedule:
    # 台灣時間 09:00 到 13:30 (UTC 1:00 到 5:30)，每半小時 (整點與半點) 執行一次
    #- cron: '0,30 1-5 * * 1-5'
    # 避開整數塞車潮，改在每小時的 13、33、53 分執行
    - cron: '18,38,58 * * * *'
jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py
