name: Daily Stock Checker

on:
  workflow_dispatch:
  schedule:
    # 台灣時間 09:00 到 13:30 (UTC 1:00 到 5:30)，每一小時 (15分) 執行一次
    #- cron: '15 1-5 * * 1-5'
    - cron: '15 * * * *'
jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py
